version: '3.8'

services:
  # DATABASE_URL=mysql://test:test@mysql:3306/test
  mysql:
    image: arm64v8/mysql:oracle
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./.mysql:/var/lib/mysql
